trigger:
- main

pool:
  name: Default

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore WebApp/WebApp.csproj
  displayName: 'Restore packages'

- script: dotnet build WebApp/WebApp.csproj -c Release --no-restore
  displayName: 'Build project'

- script: dotnet pack WebApp/WebApp.csproj -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'WebApp/bin/Release/net8.0'
    ArtifactName: 'drop'
    publishLocation: 'Container'
